version: '3.1'

services:

  postgre:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgre
      POSTGRES_PASSWORD: 123
      DB_HOST: host.docker.internal

