version: '3.1'

services:

  postgre:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgre
      POSTGRES_PASSWORD: 123
      DB_HOST: host.docker.internal

  elasticsearch:
    image: elasticsearch:8.7.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      xpack.security.enrollment.enabled: false